name: egnn-qm9
channels:
  - conda-forge
  - pyg
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipykernel
  - pytorch
  - egnn-pytorch
  - matplotlib
  - pyg # pytorch-geometric
  - pip:
    - python-dotenv
    - mkdocs
    - -e .